import React from "react";
import type { Metadata } from "next";
import { Anton } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../context/theme-context";
import { UserProvider } from "../context/usercontext";
import { ImageProvider } from "@/context/imagekitContext";

const antonFont = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Forge App",
  description: "Generated by create-forgestack",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${antonFont.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <UserProvider>
            <ImageProvider>
              {children}
            </ImageProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}